# EJERCICIO 1: Proceso Análisis Exploratorio
Ejercicio para practicar la introducción al EDA (Exploratory Data Analysis).

# Objetivo: EDA TITANIC
Este dataset contiene un registro real de las personas que embarcaron en el mismo, con variables como sexo, edad, tipo de billete... y la más truculenta de todas: si esa persona falleció o no.

En este ejercicio estudiaremos haremos un análisis exploratorio de este Dataset.

# 01 Import
Importamos pandas y numpy.

In [1]:
import pandas as pd
import numpy as np

# 02 Load Data
Como ya hemos comentado, Kaggle es uno de los lugares de referencia para estudiar ciencia de datos. Entra en Kaggle, busca el dataset del Titanic y cárgalo este Notebook como tu prefieras.

(Probablemente encuentres dos: train y test, por ahora podemos quedarnos con el train). Cárgalo a un dataframe con el nombre 'df'.

In [10]:
import pandas as pd
df = pd.read_csv('Titanic-Dataset.csv')

# Display the first few rows of the dataframe to verify it's loaded correctly
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 03 Basic checks
Una vez se han importado los datos, haz las comprobaciones básicas pertinentes para conocer el tamaño de la tabla, columnas presentes, visualizar algunos datos, conocer el tipo de dato de cada variable, etc.

In [12]:
df = pd.read_csv('Titanic-Dataset.csv')

# Visualización primeras filas
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

## 0301 Vista previa
Visualiza, fijándote en cada variable:


1.   Las 5 primeras filas
2.   Las 3 últimas filas
3.   Las filas 300 a 305

In [13]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
df.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [15]:
df.iloc[300:305, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
300,301,1,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,9234,7.75,NaN,Q
301,302,1,3,"McCoy, Mr. Bernard",male,NaN,2,0,367226,23.25,NaN,Q
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.00,NaN,S
303,304,1,2,"Keane, Miss. Nora A",female,NaN,0,0,226593,12.35,E101,Q
304,305,0,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.05,NaN,S

## 0302 Tamaño
Cuantos pasajeros hay? Y cuántas variables?

In [16]:
df.shape

(891, 12)

## 0303 Tipos de datos
Qué tipos de datos contiene nuestro dataframe?

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# 04 Limpieza de Nulos
Los nulos son habituales y un poco molestos. Constituyen una pérdida de información y pueden impedir ciertos cálculos.

Es importante detectarlos y, cuando sea posible, corregirlos.

## 0401 Nulos por variable
Cuántos nulos hay en cada variables?

In [18]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## 0402 Explorar Nulos
Cuando sea posible es recomendable entender la causa de los nulos. Hay algún patrón que se repite entre ellos?

Veámoslo para cada una de las variables con nulos:

In [19]:
cols_con_nulos = ['Age', 'Cabin', 'Embarked']

for col in cols_con_nulos:
  filtro_nulos = df[col].isna()
  filtro_no_nulos = df[col].isna()==False
  print(col.upper())
  print('Nulos:')
  display(df.loc[filtro_nulos,:].head())
  print('No nulos:')
  display(df.loc[filtro_no_nulos,:].head())
  print()

AGE
Nulos:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q

No nulos:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

CABIN
Nulos:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

No nulos:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

EMBARKED
Nulos:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

No nulos:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 0403 Tratamiento de Nulos
Una vez hemos detectado los nulos presentes en la tabla podemos corregirlos de varias formas.

### 040301 Corrección de nulos 'Age'
No parece haber una causa evidente para que algunas edades no estén imputadas. Es una variable numérica que debemos rellenar también con valores numéricos.
De más sencillo a más complejo, podríamos:


1.   Rellenar los nulos con la mediana de los valores de edad no nulos
2.   Rellenar los nulos de las mujeres con la mediana de edad de éstas, y los hombres con la suya
3.   Rellenar los nulos sirviéndonos del título en el nombre, utilizando la mediana del resto de pasajeros con el mismo título.

In [20]:
df['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [22]:
# Generamos una nueva columna edad (queremos modificar la original de varias formas)
df['Age_1'] = df['Age']

# Se rellena la columna edad con la mediana
df['Age_1'] = df['Age'].fillna(df['Age'].median())

In [24]:
filtro_mujeres = df['Sex'] == 'female'
filtro_hombres = df['Sex'] == 'male'
filtro_edad_nula = df['Age'].isna()
filtro_edad_no_nula = df['Age'].notnull()

In [25]:
# Generamos una nueva columna edad
df['Age_2'] = df['Age']

# Se rellena la columna edad con la según el genero
df.loc[((filtro_hombres)&(filtro_edad_nula)), 'Age_2'] = df.loc[((filtro_hombres)&(filtro_edad_no_nula)), 'Age'].median()
df.loc[((filtro_mujeres)&(filtro_edad_nula)), 'Age_2'] = df.loc[((filtro_mujeres)&(filtro_edad_no_nula)), 'Age'].median()

In [26]:
# Extraemos el título con una list comprehension y lo guardamos en una nueva columna
df['Titulo'] = [name.split(".")[0].split(",")[1][1:] for name in df['Name']]
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_1,Age_2,Titulo
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,22.0,22.0,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.0,38.0,Mrs

In [27]:
# Generamos una nueva columna edad
df['Age_3'] = df['Age']

# Rellenamos los nulos
for titulo in df['Titulo'].unique():
  filtro_titulo = df['Titulo'] == titulo

  if len(df[((filtro_titulo) & (filtro_edad_no_nula))]) > 1:
    print(titulo)
    df.loc[((filtro_titulo)&(filtro_edad_nula)), 'Age_3'] = df.loc[((filtro_titulo)&(filtro_edad_no_nula)), 'Age'].median()

# Rellenamos los que sigan siendo nulos (títulos solo presentes entre gente sin la edad informada)
df['Age_3'] = df['Age_3'].fillna(df['Age_3'].median())

Mr
Mrs
Miss
Master
Rev
Dr
Major
Mlle
Col

In [28]:
df[['Age', 'Age_1', 'Age_2', 'Age_3']].describe()

              Age       Age_1       Age_2       Age_3
count  714.000000  891.000000  891.000000  891.000000
mean    29.699118   29.361582   29.441268   29.390202
std     14.526497   13.019697   13.018747   13.265322
min      0.420000    0.420000    0.420000    0.420000
25%     20.125000   22.000000   22.000000   21.000000
50%     28.000000   28.000000   29.000000   30.000000
75%     38.000000   35.000000   35.000000   35.000000
max     80.000000   80.000000   80.000000   80.000000

### 040302 Corrección de nulos 'Embarked'
Solo hay dos nulos aquí, así que vamos a eliminar estas dos filas.

In [29]:
df.dropna(subset=['Embarked'],inplace=True)

In [ ]:
# En cuanto a la columna 'Cabin', hay muchos nulos. Es además una
# columna no numérica, así que vamos a dejarlos sin tocar al menos de momento.

In [30]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
Age_1            0
Age_2            0
Titulo           0
Age_3            0
dtype: int64

# 05 Limpieza de datos
A veces los datos se encuentran en formatos no adecuados.Pero esta vez no es así :).

Sí podemos eliminar la columna PassengerId, que es redundante con el índice.

In [31]:
df.drop('PassengerId', axis=1, inplace=True)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_1,Age_2,Titulo,Age_3
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,22.0,22.0,Mr,22.0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.0,38.0,Mrs,38.0
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,26.0,26.0,Miss,26.0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,35.0,35.0,Mrs,35.0
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.0,35.0,Mr,35.0

# 06 Distribución de variables
Veamos cómo se distribuyen los valores del dataframe.

## 0601 Variables numéricas
En cuanto a las variables de tipo numérico, cuáles son su media y estadísticos más importantes.

In [32]:
df.describe()

,Survived,Pclass,Age,SibSp,Parch,Fare,Age_1,Age_2,Age_3
count,889.000000,889.000000,712.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000
mean,0.382452,2.311586,29.642093,0.524184,0.382452,32.096681,29.315152,29.395017,29.343836
std,0.486260,0.834700,14.492933,1.103705,0.806761,49.697504,12.984932,12.984264,13.231853
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.420000,0.420000,0.420000
25%,0.000000,2.000000,20.000000,0.000000,0.000000,7.895800,22.000000,22.000000,21.000000
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,28.000000,29.000000,30.000000
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,35.000000,35.000000,35.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,80.000000,80.000000,80.000000

## 0602 Variables categóricas
Aquellas que pueden adoptar valores finitos.

In [33]:
df['Survived'].value_counts()

Survived
0    549
1    340
Name: count, dtype: int64

In [34]:
df['Pclass'].value_counts()

Pclass
3    491
1    214
2    184
Name: count, dtype: int64

In [35]:
df['Sex'].value_counts()

Sex
male      577
female    312
Name: count, dtype: int64

In [36]:
df['SibSp'].value_counts()

SibSp
0    606
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

In [37]:
df['Parch'].value_counts()

Parch
0    676
1    118
2     80
5      5
3      5
4      4
6      1
Name: count, dtype: int64

In [38]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

# 07 Preguntas sobre el dataset

De entre todos los pasajeros,
### Qué % falleció?

In [39]:
perc_fallecidos = (1-df['Survived'].mean())*100
print('Falleció un '+str(round(perc_fallecidos,2))+'%')

Falleció un 61.75%

Es bastante famoso lo de "mujeres y niños" primero, sería cierto en el caso del Titanic?
### Qué % de mujeres y hombres fallecieron?
### Qué % de niños (menores de 10) y adultos (mayores) fallecieron?

In [40]:
fallecidos_vs_genero = df.groupby('Sex')['Survived'].mean().reset_index()
fallecidos_vs_genero['Fallecidos'] = 1 - fallecidos_vs_genero['Survived']
fallecidos_vs_genero

      Sex  Survived  Fallecidos
0  female  0.740385    0.259615
1    male  0.188908    0.811092

In [41]:
filtro_niño = df['Age'] < 10
filtro_adulto = df['Age'] >= 10

fallecidos_niños = (1-df.loc[filtro_niño,'Survived'].mean())
fallecidos_adulto = (1-df.loc[filtro_adulto,'Survived'].mean())

print('Fallecidos entre niños: '+str(round(fallecidos_niños*100,2)))
print('Fallecidos entre adultos: '+str(round(fallecidos_adulto*100,2)))

Fallecidos entre niños: 38.71
Fallecidos entre adultos: 61.54

Pues parece que en el Titanic sí se cumplió lo de "mujeres y niños primero". En la película también se salvaba más la gente de clase alta, con dinero, será cierto?
### Qué % fallece según su clase de billete (1, 2, 3)?

In [42]:
fallecidos_vs_clase = df.groupby('Pclass')['Survived'].mean().reset_index()
fallecidos_vs_clase['Fallecidos'] = 1 - fallecidos_vs_clase['Survived']
fallecidos_vs_clase

   Pclass  Survived  Fallecidos
0       1  0.626168    0.373832
1       2  0.472826    0.527174
2       3  0.242363    0.757637

Incidamos en esto.

### Qué % fallece entre los 50 que pagaron más por su billete y los 50 que menos?

In [43]:
df_orden = df.sort_values('Fare', ascending=False)

df_orden['Survived'][:50].mean()

0.74

In [44]:
df_orden['Survived'][-50:].mean()

0.1

Los pasajeros embarcaron desde 3 puertos,

### En alguno falleció más porcentaje de gente que en el resto?

In [45]:
df.groupby('Embarked')['Survived'].mean().reset_index()

  Embarked  Survived
0        C  0.553571
1        Q  0.389610
2        S  0.336957